version: "3.8"
services:
  help:
    container_name: webshophelp_test
    image: brhv/webshophelp
    restart: unless-stopped
    ports:
      - 18000:80
    networks:
      - testbacktier
    environment:
      - SERVER=webshopdatabase_test
  seq:
    container_name: SeQ_test
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - 18081:80
      - 15341:5341
    networks:
      - testbacktier
    environment:
      - ACCEPT_EULA=Y
  smtp4dev:
    container_name: smtp4dev_test
    image: rnwood/smtp4dev:latest
    ports:
      - 18082:80
      - 1026:25
    networks:
      - testbacktier
  paymentapi:
    container_name: webshop_payment_test
    image: brhv/webshoppaymentapi
    restart: unless-stopped
    ports:
      - 18083:80
    networks:
      - testbacktier
    environment:
      - ConnectionStrings__DefaultConnection=Server=webshopdatabase_test;Database=psuwebshop;User=sa;Password=PSU@password;
  catalogapi:
    container_name: webshop_catalog_test
    image: brhv/webshopcatalogapi
    restart: unless-stopped
    ports:
      - 18084:80
    networks:
      - testbacktier
    environment:
      - ConnectionStrings__DefaultConnection=Server=webshopdatabase_test;Database=psuwebshop;User=sa;Password=PSU@password;
  customerapi:
    container_name: webshop_customer_test
    image: brhv/webshopcustomerapi
    restart: unless-stopped
    ports:
      - 18085:80
    networks:
      - testbacktier
    environment:
      - ConnectionStrings__DefaultConnection=Server=webshopdatabase_test;Database=psuwebshop;User=sa;Password=PSU@password;
  sqlexpress:
    container_name: webshopdatabase_test
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    ports:
      - 11433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PSU@password
      - MSSQL_PID=Express
    volumes:
      - ./test_data:/var/opt/mssql/data
    networks:
      - testbacktier
networks:
  testbacktier: {}

volumes:
  mssql_data: {}
